### ISSUE TITLE
ModuleNotFoundError: No module named 'mistune'

### ISSUE THREAD

**Issue by Dorian** [regardscitoyens/anpy#5]
```bash
pip3 install anpy
...
python3 -c "from anpy.dossier import Dossier"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/d/src/clones/anpy/anpy/dossier.py", line 8, in <module>
    import mistune
ModuleNotFoundError: No module named 'mistune'
```

**Comment by Dorian** [comment]
`pip3 install -e .` fixed it
